### ISSUE TITLE
install-spark should ignore case when searching for values

### ISSUE THREAD

**Issue by derrickburns** [awslabs/emr-bootstrap-actions#42] opened 2015-01-15 05:33 UTC
the various "grep" calls in "maximize-spark-default-config" are searching for upper case values like "CORE" when the values are actually in mixed case if the user uses lower case to name instance groups.

**Comment by christopherbozeman** [comment] 2015-01-15 18:40
Thanks for the report!   This is a duplicate of issue https://github.com/awslabs/emr-bootstrap-actions/issues/38.   Improvements have been made to "maximize-spark-default-config" use yarn node list instead of group based on name.

**Comment by christopherbozeman** [comment] 2015-02-13 22:08
Derrick  - is this resolved?

**Comment by derrickburns** [comment] 2015-02-13 22:17
Checking now.

BTW, how do I access ganglia for a spark cluster?  I seem to have forgotten
the magic.

**Comment by christopherbozeman** [comment] 2015-02-13 22:19
Ganglia is on port 80 of the master node. `http://<masternode>/ganglia/`.   The specific Spark metrics appear under whichever node was running the driver.

**Comment by derrickburns** [comment] 2015-02-13 22:24
thx!

**Comment by derrickburns** [comment] 2015-02-13 22:56
That doesn't work for me on j-2Q17MKCBYWEJ7. Ideas?

**Comment by derrickburns** [comment] 2015-02-16 16:58
Do I need to install ganglia with a bootstrap action? If so, how?

**Comment by christopherbozeman** [comment] 2015-02-16 17:50
Yes, Ganglia has to be installed, too.  See http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/UsingEMR_Ganglia.html#init_Ganglia

**Comment by derrickburns** [comment] 2015-02-16 21:04
Unfortunately, this page does not specify the bootstrap action to use when
NOT using the AWS command line tools (which I am not).   I tried using this
bootstrap action (run with the script-runner), but it failed:

s3://elasticmapreduce/bootstrap-actions/install-ganglia

Ideas?

**Comment by christopherbozeman** [comment] 2015-02-16 23:13
I see. Just use 's3://elasticmapreduce/bootstrap-actions/install-ganglia'
as bootstrap without script runner.

**Comment by derrickburns** [comment] 2015-02-17 00:38
Thx!

**Closed** 2015-02-25 00:38 UTC
