### ISSUE TITLE
Presto query fails when querying on S3 external table

### ISSUE THREAD

**Issue by achiku** [awslabs/emr-bootstrap-actions#33] opened 2015-01-07 06:55 UTC
Hi,

### Basic Info
- AMI Version: 3.3.1
- Hive Version: 0.13.1
- Presto Version: 0.78
- All EC2 instances are in VPC public subnet (default gateway is InternetGateway)
- Using EMR_EC2_DefaultRole/EMR_DefaultRole
- Start EMR by boto==2.34.0

start command line
```
aws emr create-cluster --ami-version 3.3.1 \
    --name " (AMI 3.3.1 Hive + Presto) $( date '+%Y%m%d%H%M' )" \
    --service-role EMR_DefaultRole \
    --tags Name=production-emr environment=production \
    --ec2-attributes KeyName=[KEY],InstanceProfile=EMR_EC2_DefaultRole,SubnetId=[SUBNET] \
    --applications file://./app-hive-hue.json \
    --instance-groups file://./large-instance-setup.json \
    --bootstrap-actions file://./bootstrap-presto.json \
    --log-uri 's3://[BUCKET]/jobflow_logs/' \
    --no-auto-terminate \
    --visible-to-all-users
```

- app-hive.json
```
[
  {
    "Name": "HIVE"
  }
]
```

- large-instance-setup.json
```
[
  {
     "Name": "emr-master-production",
     "InstanceGroupType": "MASTER",
     "InstanceCount": 1,
     "InstanceType": "r3.xlarge"
  },
  {
     "Name": "emr-core-production",
     "InstanceGroupType": "CORE",
     "InstanceCount": 2 ,
     "InstanceType": "r3.xlarge"
  }
]
```

-  bootstrap-presto.json

```
[
  {
    "Name": "Install/Setup Presto",
    "Path": "s3://development-env-log/libs/install-presto.rb",
  }
]
```

### How it fails

After created pv_detail table (it's external table which data are on S3) from hive.

```
[hadoop@ip-10-0-0-236 ~]$ ./presto --catalog=hive
presto:default> show tables;
       Table
--------------------
 pv_detail
 sample_07
 sample_08
(3 rows)

Query 20150107_064546_00008_ch8y3, FINISHED, 2 nodes
Splits: 2 total, 2 done (100.00%)
0:00 [3 rows, 191B] [62 rows/s, 3.85KB/s]

presto:default> select * from pv_detail;

Query 20150107_064555_00009_ch8y3, FAILED, 1 node
Splits: 1 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20150107_064555_00009_ch8y3 failed: AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3 URL, or by setting the fs.s3.awsAccessKeyId or fs.s3.awsSecretAccessKey properties (respectively).
presto:default>
```

### When it works
When I use sample commands on README, it works fine.
https://github.com/awslabs/emr-bootstrap-actions/tree/master/presto

### Other S3 access from master node
Since aws-cli on master node  ```aws s3 ls s3://path/to/pv_detail/``` works just fine, EC2 instances must have proper right to access to S3 object.

**Comment by 8maki** [comment] 2015-01-15 05:11
me too.

**Comment by croblee** [comment] 2015-01-22 01:09
Facing a similar issue, but I get the error even with the sample commands in the README:

presto:default> select * from apachelog;
Query 20150121_233928_00009_axsg9, FAILED, 1 node
http://localhost:8080/v1/query/20150121_233928_00009_axsg9?pretty
Splits: 1 total, 0 done (0.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 0% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20150121_233928_00009_axsg9 failed: AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3 URL, or by setting the fs.s3.awsAccessKeyId or fs.s3.awsSecretAccessKey properties (respectively).
com.facebook.presto.spi.PrestoException: AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3 URL, or by setting the fs.s3.awsAccessKeyId or fs.s3.awsSecretAccessKey properties (respectively).
	at com.facebook.presto.hive.HiveSplitSourceProvider$HiveSplitSource.propagatePrestoException(HiveSplitSourceProvider.java:599)
	at com.facebook.presto.hive.HiveSplitSourceProvider$HiveSplitSource.getNextBatch(HiveSplitSourceProvider.java:542)
	at com.facebook.presto.execution.ConnectorAwareSplitSource.getNextBatch(ConnectorAwareSplitSource.java:46)
	at com.facebook.presto.execution.SqlStageExecution.scheduleSourcePartitionedNodes(SqlStageExecution.java:646)
	at com.facebook.presto.execution.SqlStageExecution.startTasks(SqlStageExecution.java:565)
	at com.facebook.presto.execution.SqlStageExecution.access$200(SqlStageExecution.java:97)
	at com.facebook.presto.execution.SqlStageExecution$4.run(SqlStageExecution.java:537)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3 URL, or by setting the fs.s3.awsAccessKeyId or fs.s3.awsSecretAccessKey properties (respectively).
	at org.apache.hadoop.fs.s3.S3Credentials.initialize(S3Credentials.java:70)
	at com.facebook.presto.hive.PrestoS3FileSystem.getAwsCredentials(PrestoS3FileSystem.java:447)
	at com.facebook.presto.hive.PrestoS3FileSystem.initialize(PrestoS3FileSystem.java:145)
	at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:74)
	at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:61)
	at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:43)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:367)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:287)
	at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:60)
	at com.facebook.presto.hive.HiveSplitSourceProvider.loadPartitionSplits(HiveSplitSourceProvider.java:223)
	at com.facebook.presto.hive.HiveSplitSourceProvider.access$100(HiveSplitSourceProvider.java:81)
	at com.facebook.presto.hive.HiveSplitSourceProvider$2.run(HiveSplitSourceProvider.java:170)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.facebook.presto.hive.util.BoundedExecutor.executeOrMerge(BoundedExecutor.java:82)
	at com.facebook.presto.hive.util.BoundedExecutor.access$000(BoundedExecutor.java:41)
	at com.facebook.presto.hive.util.BoundedExecutor$1.run(BoundedExecutor.java:53)
	... 3 more

I am using a custom instance profile.  Does the PrestoS3FileSystem support instance profile credentials?

**Comment by pmanwatkar** [comment] 2015-02-09 07:24
@achiku were you able to resolve this issue. I am facing this issue even after providing all s3 access to the instance. It worked fine with Hive though.

**Comment by pmanwatkar** [comment] 2015-02-17 10:59
@achiku I got this resolved by creating a EMR cluster without any service-role or instance-profile-role.
When you use IAM roles, core-site.xml will not have these things:
fs.s3n.awsAccessKeyId
 fs.s3.awsAccessKeyId
fs.s3bfs.awsAccessKeyId

And presto only get access creds from these properties.

**Comment by achiku** [comment] 2015-02-26 02:57
@pmanwatkar  Yeah, we did the same. But I really don't want to use accesskey/secret since we have to store them in somewhere. I talked to AWS support, but this behavior will not be fixed soon.

**Comment by pmanwatkar** [comment] 2015-02-26 04:51
I raised a ticket with AWS and they have now changed the presto bootstrap location to:
s3://support.elasticmapreduce/bootstrap-actions/presto/install-presto.rb

Try this out it will work on IAM roles as well.

**Comment by achiku** [comment] 2015-03-19 09:33
@pmanwatkar I haven't noticed but this is great news! Thanks!

**Closed** 2015-03-19 09:33 UTC
